language: python
sudo: false

matrix:
  include:
    - os: linux
      env: SETUP="linux, python 3.2, flake8"
      python: 3.2
      before_install:
        - pip3 install flake8
        - pip3 install pylint
      after_success:
        - flake8 --max-line-length 100 --ignore E402 *.py tests/*.py
        # - pylint --disable=F0401,C0413,W0201 *.py tests/*.py
    - os: linux
      env: SETUP="linux, python 3.6"
      python: 3.6

install:

before_script:
   - uname -a
   - python --version
   - python3 --version
   - bash --version

script:
   - python3 tests/run_tests.py

after_success:

after_failure:

after_script:
   - ls -al

notifications:
  email: false
