language: python
sudo: false

matrix:
  include:
    - os: linux
      env: SETUP="linux, python 3.2, flake8"
      python: 3.2
      before_install:
        - pip3 install flake8
        - pip3 install pylint
      after_success:
        - flake8 --max-line-length 100 --ignore E402 --exclude pyte,stubs
    - os: linux
      env: SETUP="linux, python 3.6"
      python: 3.6
    - os: osx
      env: SETUP="osx"
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate

install:

before_script:
   - uname -a
   - python --version
   - python3 --version
   - bash --version

script:
   - python3 tests/run_tests.py

after_success:

after_failure:

after_script:
   - ls -al

notifications:
  email: false
